# Generated by Django 3.2.9 on 2022-10-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('question_type', models.IntegerField(choices=[('MCQs', 1), ('True / False', 2), ('Phone', 3), ('Location', 4), ('Date', 5)])),
                ('required', models.BooleanField(default=False)),
                ('choices', models.ManyToManyField(related_name='choices', to='survey.Choices')),
            ],
        ),
    ]
