# Generated by Django 3.2.9 on 2022-10-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'MCQs'), (2, 'True / False'), (3, 'Phone'), (4, 'Location'), (5, 'Date')]),
        ),
    ]
